// Copyright (c) 2026 David Bertet. Licensed under the MIT License.

// Generic read/write for the gitignored backend/src/secrets.h header.
// Real secrets (OTA password, WiFi credentials) live there so tracked
// constants.h keeps placeholders and stays committable. secrets.h overrides
// via `#undef` + `#define` and is pulled in at the end of constants.h.

const fs = require('fs')
const path = require('path')

const SECRETS_HEADER = path.resolve(__dirname, '..', '..', 'backend', 'src', 'secrets.h')

function escapeCString(value) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function secretsTemplate() {
  return '#pragma once\n\n// Auto-generated by install tooling. DO NOT COMMIT.\n// Gitignored (see backend/.gitignore) so real secrets never reach git.\n'
}

function unescapeCString(value) {
  return value.replace(/\\"/g, '"').replace(/\\\\/g, '\\')
}

// Insert or replace the `#undef NAME / #define NAME "value"` block.
function upsertSecret(content, name, value) {
  const escaped = escapeCString(value)
  const block = `#undef ${name}\n#define ${name} "${escaped}"`
  const regex = new RegExp(
    `(?:#undef\\s+${name}\\s*\\n)?#define\\s+${name}\\s+"(?:[^"\\\\]|\\\\.)*"`,
  )
  if (regex.test(content)) {
    return content.replace(regex, block)
  }
  return content.replace(/\s*$/, '') + `\n${block}\n`
}

function readSecret(content, name) {
  const match = content.match(defineRegex(name))
  return match ? unescapeCString(match[1]) : null
}

function defineRegex(name) {
  return new RegExp(`#define\\s+${name}\\s+"((?:[^"\\\\]|\\\\.)*)"`)
}

function loadSecrets(headerPath = SECRETS_HEADER) {
  try {
    return fs.readFileSync(headerPath, 'utf8')
  } catch {
    return secretsTemplate()
  }
}

function writeSecrets(updates, headerPath = SECRETS_HEADER) {
  let content = loadSecrets(headerPath)
  for (const [name, value] of Object.entries(updates)) {
    content = upsertSecret(content, name, value)
  }
  fs.writeFileSync(headerPath, content)
}

module.exports = {
  SECRETS_HEADER,
  secretsTemplate,
  escapeCString,
  unescapeCString,
  upsertSecret,
  readSecret,
  loadSecrets,
  writeSecrets,
}
